In [1]:
import numpy as np
from Bio import SeqIO
from Bio.Seq import Seq
from mutate import mutate

In [8]:
def unfold_series (file,path):
    for i in np.arange(2, 12, 2):
        pos = np.arange(144-(2*(i)), 145, 2)
        print(pos)
        residues = ['G'] * pos.shape[0]
        name = f'{path}AsLOV_Gly2_{i+1}'
        mutate(file, pos, residues, name)

In [9]:
file = '/home/leonardo/Solution_Scattering_2208/AsLOV2/Unfolding_test/AsLOV2.fasta'
path = '/home/leonardo/Solution_Scattering_2208/AsLOV2/Unfolding_test/'
unfold_series(file, path)

[140 142 144]
140
G
142
G
144
G
[136 138 140 142 144]
136
G
138
G
140
G
142
G
144
G
[132 134 136 138 140 142 144]
132
G
134
G
136
G
138
G
140
G
142
G
144
G
[128 130 132 134 136 138 140 142 144]
128
G
130
G
132
G
134
G
136
G
138
G
140
G
142
G
144
G
[124 126 128 130 132 134 136 138 140 142 144]
124
G
126
G
128
G
130
G
132
G
134
G
136
G
138
G
140
G
142
G
144
G
